spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  sleuth:
    enabled: true
      sampler:
        percentage: 1
  zipkin:
    enabled: true
      baseUrl: http://localhost:9411

    
