spring:
  datasource:
    url: jdbc:mysql://localhost/db_showroom
    username: root
    password: root
    
car-uri: http://showroomRibbon/MicroService/car/details/
owner-uri: http://localhost:4102/MicroService/owner/details/
